#+AUTHOR:  Ashley Gillman
#+TITLE: STIR Docker Readme

[[http://stir.sourceforge.net/][STIR]], Dockerised.

* STIR Docker
A Docker image based on Ubuntu Trusty, loaded with STIR's
dependencies, and with STIR built from source. In order to use you
should make sure you register for STIR [[http://stir.sourceforge.net/registration][here]].

** Build
#+begin_src sh
docker build -t stir .
docker build -t stir:explore ./explore
#+end_src
Or run =build.sh=, which will also verify the installation with the
=recon_test_pack=.

** Usage
#+begin_src sh
docker run --rm -v `pwd`:/data -w /data stir OSMAPOSL /some/file.par
#+end_src

If using often from command line you could set up an alias.
#+begin_src sh
alias stir="docker run --rm -v `pwd`:/data -w /data stir
#+end_src

Use the =stir:explore= image to launch an interactive session.

** Dependencies Installed
The Dockerfile currently installs:
- CMake
- Boost
- ITK 3
- Curses
- libtiff
- MPI

The file also uses the [[https://github.com/krallin/tini][Tini]] spawner, to ensure that all processes are
appropriately cleaned up.

** TODO Possible Further Development
- [ ] Open MP
- [ ] VTK
- [ ] Dependencies for python/MATLAB support (swig etc.)

* Authorship
I did not write STIR. My contribution is nothing more that a handful
of files no longer than 20 lines long. Full credits for contributions
to STIR can be found [[http://stir.sourceforge.net/credits.htm][here]].

* License
This small package is released under the GPL license, in accordance
with [[http://stir.sourceforge.net/registration][STIR's licensing]]. Please refer to STIR's licensing for any
queries about the STIR package.
